
# This playbook installs nginx on the web servers and deploys a custom homepage using a Jinja2 template.


- name: Install nginx and deploy homepage
  hosts: web
  become: yes

  vars:
    my_name: "Zsolt Csengeri"

  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Ensure nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: "0644"
